version: 2

references:
  restore_npm_cache: &restore_npm_cache
    restore_cache:
      keys:
        # when lock file changes, use increasingly general patterns to restore cache
        - npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
        - npm-packages-v1-{{ .Branch }}-
        - npm-packages-v1-

  save_npm_cache: &save_npm_cache
    save_cache:
      paths:
        - node_modules/
      key: npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/spokestack
    steps:
      - checkout
      - *restore_npm_cache
      - run: npm install --no-save
      - *save_npm_cache

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Run build
          command: npm run build

      - persist_to_workspace:
          root: ~/spokestack
          paths:
            - public

workflows:
  version: 2

  test_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only:
                - /\d+\.\d+\.\d+/
